name: Node.js CI and Print Script

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NAME: ${{ vars.NEW_NAME }}
      TALENT: ${{ secrets.PERSON }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run Shell Script
        run: ./print_message.sh
